user:
  name:
    presence: true
    length:
      maximum: 50
  password:
    presence: true
    length:
      minimum: 6

post:
  content:
    presence: true
    length:
      maximum: 140
  image:
    content_type:
      in: ["image/jpeg", "image/gif", "image/png"]
      message: "must be a valid image format"
    size:
      less_than: 5.megabytes
      message: "should be less than 5MB"
    variant:
      resize_to_limit: [500, 500]

